#!/usr/bin/env bash
set -euo pipefail

# OpenClaw VPS bootstrap (Ubuntu 22.04/24.04)
# - Basic hardening (user, sshd, ufw, fail2ban, unattended upgrades)
# - Installs Node.js 22, pnpm, and OpenClaw
# - Safe to re-run after interruption (uses a small state file + checkpoints)

# Usage:
#   curl -fsSL <raw-url> | sudo bash
# or:
#   sudo bash setup.sh
#
# Options:
#   --force              Re-run all steps even if previously marked complete
#   --skip-ssh-hardening Skip SSH hardening changes (useful if you need to install deps first)

if [[ ${EUID:-0} -ne 0 ]]; then
  echo "ERROR: run as root (sudo)." >&2
  exit 1
fi

log() { printf "\n==> %s\n" "$*"; }
warn() { printf "\nWARNING: %s\n" "$*" >&2; }
err() { printf "\nERROR: %s\n" "$*" >&2; }

require_cmd() {
  command -v "$1" >/dev/null 2>&1 || {
    err "Missing required command: $1"
    exit 1
  }
}

FORCE=0
SKIP_SSH_HARDENING=0
for arg in "$@"; do
  case "$arg" in
    --force) FORCE=1 ;;
    --skip-ssh-hardening) SKIP_SSH_HARDENING=1 ;;
    *) err "Unknown arg: $arg"; exit 1 ;;
  esac
done

STATE_DIR="/var/lib/openclaw-setup"
STATE_FILE="$STATE_DIR/state.env"
DONE_FILE="$STATE_DIR/done.list"
mkdir -p "$STATE_DIR"

is_done() {
  [[ -f "$DONE_FILE" ]] && grep -Fxq "$1" "$DONE_FILE"
}
mark_done() {
  mkdir -p "$STATE_DIR"
  touch "$DONE_FILE"
  if ! grep -Fxq "$1" "$DONE_FILE"; then
    echo "$1" >> "$DONE_FILE"
  fi
}

load_state() {
  if [[ -f "$STATE_FILE" ]]; then
    # shellcheck disable=SC1090
    source "$STATE_FILE" || true
  fi
}

save_state() {
  cat >"$STATE_FILE" <<EOF
# Generated by OpenClaw setup.sh. Safe to edit.
OC_USER=${OC_USER}
SSH_PORT=${SSH_PORT}
DISABLE_PW=${DISABLE_PW}
DISABLE_ROOT=${DISABLE_ROOT}
INSTALL_TS=${INSTALL_TS}
ADD_SWAP=${ADD_SWAP}
EOF
  chmod 600 "$STATE_FILE" || true
}

load_state

DEFAULT_USER="${OC_USER:-openclaw}"
DEFAULT_SSH_PORT="${SSH_PORT:-22}"

read -r -p "Create/use non-root user [${DEFAULT_USER}]: " OC_USER
OC_USER=${OC_USER:-$DEFAULT_USER}

read -r -p "SSH port [${DEFAULT_SSH_PORT}] (keep 22 unless you know why): " SSH_PORT
SSH_PORT=${SSH_PORT:-$DEFAULT_SSH_PORT}

read -r -p "Disable password SSH auth? [Y/n]: " DISABLE_PW
DISABLE_PW=${DISABLE_PW:-${DISABLE_PW:-Y}}

read -r -p "Disable root SSH login? [Y/n]: " DISABLE_ROOT
DISABLE_ROOT=${DISABLE_ROOT:-${DISABLE_ROOT:-Y}}

read -r -p "Install Tailscale? [y/N]: " INSTALL_TS
INSTALL_TS=${INSTALL_TS:-${INSTALL_TS:-N}}

read -r -p "Add swap file (recommended for 1–2GB RAM)? [Y/n]: " ADD_SWAP
ADD_SWAP=${ADD_SWAP:-${ADD_SWAP:-Y}}

save_state

has_installed_ssh_key() {
  local path="$1"
  [[ -f "$path" ]] && grep -Eq '^ssh-(ed25519|rsa) ' "$path" 2>/dev/null
}

# Ask for pubkey only if we haven't already successfully installed one.
SSH_PUBKEY=""
HOME_DIR="/home/${OC_USER}"
AUTH_KEYS="${HOME_DIR}/.ssh/authorized_keys"
if ! has_installed_ssh_key "$AUTH_KEYS"; then
  echo
  echo "SSH KEY SETUP (recommended)"
  echo "Run these on your laptop BEFORE continuing:"
  echo "  1) Generate a key if you don't have one:"
  echo "       ssh-keygen -t ed25519 -C \"your_email@example.com\""
  echo "  2) Print/copy your public key:"
  echo "       cat ~/.ssh/id_ed25519.pub"
  echo
  echo "Paste the full line (starts with 'ssh-ed25519 ...') when prompted below."
  echo
  read -r -p "Paste your SSH public key for the '${OC_USER}' user (optional but recommended): " SSH_PUBKEY
  SSH_PUBKEY=${SSH_PUBKEY:-}
else
  log "Existing SSH authorized_keys detected for ${OC_USER}; skipping pubkey prompt"
fi

step() {
  local key="$1"; shift

  # Special case: if ssh_pubkey was marked done but no key is actually installed,
  # do NOT skip it. This can happen if a previous run was interrupted or the user
  # skipped the pubkey prompt.
  if [[ "$key" == "ssh_pubkey" ]] && [[ $FORCE -eq 0 ]] && is_done "$key"; then
    if ! has_installed_ssh_key "$AUTH_KEYS"; then
      warn "Checkpoint 'ssh_pubkey' was set but no key is installed at $AUTH_KEYS; re-running key install step"
    else
      log "Skipping (already done): $key"
      return 0
    fi
  elif [[ $FORCE -eq 0 ]] && is_done "$key"; then
    log "Skipping (already done): $key"
    return 0
  fi

  "$@"

  # Only mark ssh_pubkey as done if a key is actually installed.
  if [[ "$key" == "ssh_pubkey" ]]; then
    if has_installed_ssh_key "$AUTH_KEYS"; then
      mark_done "$key"
    else
      warn "ssh_pubkey step did not install a key (yet); leaving checkpoint unset"
    fi
  else
    mark_done "$key"
  fi
}

install_base_packages() {
  log "Updating apt + installing base packages"
  export DEBIAN_FRONTEND=noninteractive
  apt-get update
  apt-get install -y --no-install-recommends \
    ca-certificates curl git gnupg lsb-release \
    ufw fail2ban unattended-upgrades apt-listchanges \
    jq
}

create_user_and_sudo() {
  log "Creating user: ${OC_USER} (if missing)"
  if ! id -u "$OC_USER" >/dev/null 2>&1; then
    adduser --disabled-password --gecos "" "$OC_USER"
  fi

  log "Adding ${OC_USER} to sudo group"
  usermod -aG sudo "$OC_USER"
}

authorize_pubkey() {
  if [[ -z "$SSH_PUBKEY" ]]; then
    warn "No SSH public key provided. You'll need to add one before disabling password/root SSH."
    return 0
  fi

  log "Authorizing your SSH public key for user: ${OC_USER}"
  local ssh_dir="${HOME_DIR}/.ssh"

  install -d -m 700 -o "$OC_USER" -g "$OC_USER" "$ssh_dir"
  touch "$AUTH_KEYS"
  chown "$OC_USER":"$OC_USER" "$AUTH_KEYS"
  chmod 600 "$AUTH_KEYS"

  if ! grep -Fqx "$SSH_PUBKEY" "$AUTH_KEYS" 2>/dev/null; then
    echo "$SSH_PUBKEY" >>"$AUTH_KEYS"
  fi
}

ensure_safe_to_harden_ssh() {
  if [[ $SKIP_SSH_HARDENING -eq 1 ]]; then
    warn "Skipping SSH hardening due to --skip-ssh-hardening"
    return 1
  fi

  # If either hardening toggle is requested, we require a working key on disk.
  if [[ "$DISABLE_PW" =~ ^[Yy]$ ]] || [[ "$DISABLE_ROOT" =~ ^[Yy]$ ]]; then
    if ! has_installed_ssh_key "$AUTH_KEYS"; then
      err "SSH hardening requested, but no SSH public key is installed at: $AUTH_KEYS"
      err "To avoid locking you out, re-run this script and paste your public key when prompted, or run with --skip-ssh-hardening."
      exit 1
    fi
  fi
}

configure_sshd() {
  ensure_safe_to_harden_ssh || return 0

  log "Configuring SSHD"
  local sshd_cfg="/etc/ssh/sshd_config"
  cp -a "$sshd_cfg" "${sshd_cfg}.bak.$(date +%s)"

  mkdir -p /etc/ssh/sshd_config.d
  local ovr=/etc/ssh/sshd_config.d/99-openclaw-hardening.conf
  cat > "$ovr" <<EOF
# OpenClaw hardening overrides
Port ${SSH_PORT}
Protocol 2

# Strong defaults
ChallengeResponseAuthentication no
UsePAM yes
X11Forwarding no
AllowAgentForwarding no
AllowTcpForwarding yes

# Auth
PasswordAuthentication no
KbdInteractiveAuthentication no
EOF

  if [[ "$DISABLE_ROOT" =~ ^[Yy]$ ]]; then
    echo "PermitRootLogin no" >> "$ovr"
  fi

  # If user wants to keep passwords, flip the two lines.
  if [[ ! "$DISABLE_PW" =~ ^[Yy]$ ]]; then
    sed -i 's/^PasswordAuthentication no/PasswordAuthentication yes/' "$ovr"
    sed -i 's/^KbdInteractiveAuthentication no/KbdInteractiveAuthentication yes/' "$ovr"
    warn "Password SSH auth kept enabled. Consider disabling it after you confirm key access works."
  fi

  sshd -t
  systemctl restart ssh
}

configure_ufw() {
  log "Configuring UFW firewall"
  ufw --force reset
  ufw default deny incoming
  ufw default allow outgoing
  ufw allow "${SSH_PORT}/tcp"
  if [[ "$INSTALL_TS" =~ ^[Yy]$ ]]; then
    ufw allow 41641/udp
  fi
  ufw --force enable
}

configure_fail2ban() {
  log "Configuring fail2ban (basic sshd jail)"
  local jail_local=/etc/fail2ban/jail.local
  cat > "$jail_local" <<'EOF'
[DEFAULT]
# Ban time in seconds (1h)
bantime = 3600
findtime = 600
maxretry = 5

[sshd]
enabled = true
EOF
  systemctl enable --now fail2ban
}

enable_unattended_upgrades() {
  log "Enabling unattended upgrades"
  dpkg-reconfigure -f noninteractive unattended-upgrades || true
  systemctl enable --now unattended-upgrades || true
}

add_swap() {
  if [[ "$ADD_SWAP" =~ ^[Yy]$ ]]; then
    if ! swapon --show | grep -q .; then
      log "Adding 2G swapfile (/swapfile)"
      fallocate -l 2G /swapfile || dd if=/dev/zero of=/swapfile bs=1M count=2048
      chmod 600 /swapfile
      mkswap /swapfile
      swapon /swapfile
      if ! grep -q '^/swapfile ' /etc/fstab; then
        echo '/swapfile none swap sw 0 0' >> /etc/fstab
      fi
    else
      log "Swap already present; skipping"
    fi
  fi
}

install_node() {
  log "Installing Node.js 22 (NodeSource)"
  curl -fsSL https://deb.nodesource.com/setup_22.x | bash -
  apt-get install -y nodejs
  require_cmd node
  require_cmd npm
}

install_pnpm() {
  log "Installing pnpm"
  corepack enable || true
  corepack prepare pnpm@latest --activate || npm i -g pnpm
}

install_openclaw() {
  log "Installing OpenClaw (global)"
  npm i -g openclaw@latest
  log "OpenClaw version"
  openclaw --version || true
}

install_tailscale() {
  if [[ "$INSTALL_TS" =~ ^[Yy]$ ]]; then
    log "Installing Tailscale"
    curl -fsSL https://tailscale.com/install.sh | sh
  fi
}

step base_packages install_base_packages
step user create_user_and_sudo
step ssh_pubkey authorize_pubkey
step sshd configure_sshd
step ufw configure_ufw
step fail2ban configure_fail2ban
step unattended enable_unattended_upgrades
step swap add_swap
step node install_node
step pnpm install_pnpm
step openclaw install_openclaw
step tailscale install_tailscale

cat <<EOF

============================================================
MANUAL STEPS (you must do these)
============================================================

1) Verify SSH key login works for user '${OC_USER}'

   From your laptop:

       ssh -p ${SSH_PORT} ${OC_USER}@<server-ip>

   If this fails, DO NOT close your root SSH session.
   Re-run this script (safe to re-run):

       sudo bash setup.sh

   Tip: if you need to finish installs first without changing SSH settings:

       sudo bash setup.sh --skip-ssh-hardening

2) Run OpenClaw onboarding as '${OC_USER}':

   sudo -iu ${OC_USER}
   openclaw onboard --install-daemon

3) Recommended access pattern:
   - Keep gateway bound to 127.0.0.1
   - Use SSH tunnel from your laptop:
       ssh -N -L 18789:127.0.0.1:18789 -p ${SSH_PORT} ${OC_USER}@<server-ip>
     then open http://127.0.0.1:18789

NOTES
- This script is designed to be safe to re-run after interruption.
- If you changed SSH port, remember to update your client.

Done.
EOF
